# Generated by Django 5.2.13 on 2026-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=30)),
                ("ville", models.CharField(max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("travailleur", "Travailleur"),
                            ("non_travailleur", "Non Travailleur"),
                        ],
                        max_length=30,
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("entreprise", models.CharField(blank=True, max_length=100)),
                (
                    "salaire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("niveau_etude", models.CharField(blank=True, max_length=100)),
                ("recherche_emploi", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
